add_newline = true

format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $docker_context\
    $package\
    $rust\
    $nodejs\
    $memory_usage\
    $env_var\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
"""

